owner: tuyencaovn
repo: uauptime

sites:
  - name: UrbanAssets-API
    url: https://realestate-api.urbanassets.net/api/v1/general/value
  - name: UrbanAssets-Web
    url: https://urbanassets.net
  - name: UrbanAssets-BackOffice
    url: https://urbanassets.company

status-website:
  cname: status.urbanassets.net
  name: UrbanAssets Status
i18n:
  footer: © Urban Assets 2022 | All rights reserved
